FROM golang:alpine AS builder

WORKDIR $GOPATH/src/app/

COPY ./app.go .

#RUN GOOS=linux go build -ldflags="-w -s" -o /go/bin/app
RUN go version

FROM scratch

COPY --from=builder /go/bin/app /go/bin/app

ENTRYPOINT ["/go/bin/app"]

